service: serverless-lets-eat-food-app

provider:
  name: aws
  runtime: nodejs12.13
  region: ${opt:region, 'ap-southeast-2'}
  environment:
    FOOD_APP_USERS_TABLE: { "Ref": "DynamoDbFoodUsers" }
    FOOD_APP_ITEMS_TABLE: { "Ref": "DynamoDbFoodItems" }
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
            Resource:
        - { "Fn::GetAtt": ["DynamoDbFoodUsers", "Arn"] } 
        - { "Fn::GetAtt": ["DynamoDbFoodItems", "Arn"] }

functions:
  registerFoodUser:
    handler: food/registerUser.register
    environment:
      TABLE_NAME: { "Ref": "DynamoDbFoodUsers" }
    events:
      - http:
          path: user
          method: post
          cors: true

resources:
  Resources:
    DynamoDbFoodUsers:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain 
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.FOOD_APP_USERS_TABLE}

plugins:
  - serverless-finch

custom:
  client:
    bucketName: lets-eat-food-app-20200606
    distributionFolder: ../client/build