service: serverless-food-app-lets-eat

provider:
  name: aws
  runtime: nodejs12.x
  region: ${opt:region, 'ap-southeast-2'}
  environment:
    FOOD_APP_USERS_TABLE: "lets-eat-food-app-users-20200606"
    FOOD_APP_ITEMS_TABLE: "lets-eat-food-app-items-20200606"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.FOOD_APP_USERS_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.FOOD_APP_ITEMS_TABLE}"

functions:
  registerFoodUser:
    handler: food/registerUser.register
    events:
      - http:
          path: user
          method: post
          cors: true

resources:
  Resources:
    DynamoDbFoodUsers:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain 
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.FOOD_APP_USERS_TABLE}
    
    DynamoDbFoodItems:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.FOOD_APP_ITEMS_TABLE}

plugins:
  - serverless-finch

custom:
  client:
    bucketName: lets-eat-food-app-20200606
    distributionFolder: ../client/build